name: Tests

on: [push]

jobs:
  check:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.3
    - name: Install dependencies
      run: |
        sudo apt-get -y install zsh bash
        cp .github/workflows/iterm2.py .
        pip install -r requirements-dev.txt
    - name: Test
      run: |
        make test
    - name: Lint
      run: |
        make lint
